### PR TITLE
Fix banana and gooseberry juice having no fruit nutrition

### PR DESCRIPTION
**Pull request by leumasme**
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15384

Also reformatted the nutrition json files as they used mixed space/tab indenting, now uses 2 spaces. Should probably not squash this PR on merge and add the formatting commit ID to [.git-blame-ignore-revs](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view) so it doesn't apper in the git blame everywhere.

Note: The juices in question (+plum juice) have inconsistent food/nutrition values, thus the 2 new juices fixed here give 1.5% instead of 1% food nutrition. I believe this should be fixed in the private harvestcraft fork, which I dont have access to.

### CODE REVIEW

**Comment by Dream-Master** [comment]
@leumasme can you update buildscript and change Mod ID and Mod name to new Gradle standard

**Review by serenibyss — COMMENTED** [review]
Changes look good, saving approval for after @Dream-Master's comments are addressed

**Comment by leumasme** [comment]
Sorry, I haven't worked with Gradle much and don't know how to do that.

**Comment by Dream-Master** [comment]
@leumasme check out my dev branch. I am not sure if that is the right way.

**Comment by Dream-Master** [comment]
mergd via https://github.com/GTNewHorizons/Nutrition/commit/9367474b71d356b91dce79f66768411c518d8d38  and https://github.com/GTNewHorizons/Nutrition/commit/9367474b71d356b91dce79f66768411c518d8d38

**Pull request closed without merging**
